branches:
  only: 
    - next
matrix:
  include:
    - stage: "WebPack and Build"
    - language: android
      os: linux
      env:
        - WebPack="Android"
      jdk: oraclejdk8
      before_install: nvm install 8.11.4
      before_script:
        - cd ../demo && tns platform add android@next
        - cd ../demo-angular && tns platform add android@next
      script: 
        - cd ../demo && npm run build.plugin && npm i && tns build android --bundle --env.uglify --env.snapshot
        - cd ../publish 
        - sh pack.sh
        - cp package/*.tgz ../demo-angular/package.tgz
        - cd ../demo-angular
        - tns plugin add package.tgz
        - npm i
        - tns build android --bundle --env.uglify --env.snapshot --env.aot
    - language: android
      env: 
        - BuildAndroid="26"
      os: linux
      jdk: oraclejdk8
      before_install: nvm install 8.11.4
      before_script:
        - cd ../demo && tns platform add android@next
        - cd ../demo-angular && tns platform add android@next
      script:
        - cd ../src && npm i && npm run tsc && cd ../demo && tns build android && cd ../demo-angular && tns build android

android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.3
    - android-26
    - android-23
    - extra-android-m2repository

install:
    - echo no | npm install -g nativescript@next
    - tns usage-reporting disable
    - tns error-reporting disable
    - cd src
    - npm uninstall tns-core-modules -D && npm install tns-core-modules@next -D
    - npm uninstall nativescript-angular -D && npm install nativescript-angular@next -D
    - cd ../demo
    - npm uninstall nativescript-dev-webpack -D && npm install nativescript-dev-webpack@next -D
    - npm uninstall tns-core-modules -P && npm install tns-core-modules@next -P
    - npm uninstall nativescript-dev-typescript -D && npm install nativescript-dev-typescript@next -D
    - cd ../demo-angular
    - npm uninstall nativescript-dev-webpack -D && npm install nativescript-dev-webpack@next -D
    - npm uninstall tns-core-modules -P && npm install tns-core-modules@next -P
    - npm uninstall nativescript-angular -P && npm install nativescript-angular@next -P
    - npm uninstall nativescript-dev-typescript -D && npm install nativescript-dev-typescript@next -D
